name: nhom1_signin_up
description: "DangNhap DangKi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.3.0
  amplify_auth_cognito: ^1.3.0
  amazon_cognito_identity_dart_2: ^3.7.0
  email_validator: ^2.0.1
  http: ^1.2.2
  flutter_secure_storage: ^5.0.2
  provider: ^6.0.3
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

